name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python: [3.7, 3.8, 3.9, 3.10-dev]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: pip install tox codecov
      - name: Run tox
        # There's probably a better way to do this...
        run: tox -e $(tox -l | grep ^py$(echo "${{ matrix.python }}" | sed 's/.//;s/-dev//')- | tr '\n' ',')
      - name: Upload coverage
        run: codecov
