name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python: [3.7, 3.8, 3.9, 3.10-dev]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: pip install tox codecov
      - name: Run tox
        run: tox --skip-missing-interpreters
      - name: Upload coverage
        run: codecov
  mypy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: pip install mypy django-stubs djangorestframework-stubs
      - name: Run mypy
        run: mypy -p rest_framework_dataclasses
